### ISSUE TITLE
why is python 3.6.0 required?

### ISSUE THREAD

**Issue by dguibert** [SeisSol/seissol-spack-aid#24]
https://github.com/SeisSol/seissol-spack-aid/blob/3644a105c31f6495c2e6863391c0642992dc20b6/spack/packages/seissol-env/package.py#L76

Replacing `python@3.6.0` by `python` make it possible to compile `seissol` without any issue.
So why yhis is required? if not maybe the version constraint can be removed.

**Comment by Thomas-Ulrich** [comment]
All in all, this seissol-env package is outdated, sorry about that, and better use the seissol spack package
https://github.com/spack/spack/pull/41176/files

**Comment by dguibert** [comment]
> All in all, this seissol-env package is outdated, sorry about that, and better use the seissol spack package https://github.com/spack/spack/pull/41176/files

Ok, I didn't know that, thx.
I'll try the PR.
